version: '3.8'

services:
  flask_app:
    build: ./flask_app
    ports:
      - "6664:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./.env:/app/.env:ro  # Mount .env file as read-only
    env_file:
      - ./.env  # Use the .env file for environment variables
    restart: unless-stopped
    stop_signal: SIGINT
    depends_on:
      - generic_ctf_task
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    mem_limit: 1G
    memswap_limit: 1G
    cpus: 1.0
    pids_limit: 100
  
  generic_ctf_task:
    build: 
      context: ./generic_ctf_task
      dockerfile: Dockerfile
    image: localhost/generic_ctf_task:latest
    environment:
      - FLAG=${FLAG:-CTF{generic_flag_for_testing}}
    # Port mapping below is only for direct testing
    # When deployed by flask_app, it will use dynamic ports in the 9000-10000 range
    ports:
      - "44444:80"  # For direct testing access
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    mem_limit: 512M
    memswap_limit: 512M
    cpus: 0.5
    pids_limit: 50

networks:
  default:
    driver: bridge
