version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Доступ к Docker API

    environment:
      -leave_time = 240  # Время жизни контейнера (сек)
      - 
